### ISSUE TITLE
Tutorial - equip and dequip

### ISSUE THREAD

**Issue by AiryTheDragon** [DaDarkWizard/TextAdventure#13]
Going through the tutorial again, I noticed a minor error in the explanation.
![EquipTextError12-18-19](https://user-images.githubusercontent.com/58800410/71061710-af3a3700-2136-11ea-8fab-78925a15d102.png)

I would think that the word should be 'equip'. Then another line can explain that dequip will unequip the item.  This should be an easy fix, but I didn't want to forget about it.

**Comment by DaDarkWizard** [comment]
Outdated
