### ISSUE TITLE
Already equipped bug

### ISSUE THREAD

**Issue by AiryTheDragon** [DaDarkWizard/TextAdventure#14]
The following picture displays some odd behavior.

![AlreadyEquippedBug12-18-19](https://user-images.githubusercontent.com/58800410/71062388-59668e80-2138-11ea-8286-b217bbb7743a.png)

You can drop an equipped item.  However, if you pick it back up, the item will already be equipped.
I have two thoughts.
1) you could unequip the item before you drop it.
2) there is setting somewhere that is indicating the item is equipped even if it is not held by a player, which may (or may not) cause a conflict if the game expands and you have a player drop some equipped equipment to give to another player.

**Comment by AiryTheDragon** [comment]
Note: I dropped the dragon slaying longsword before attacking the bat without dequipping it, and the longsword command was still there in battle.

**Comment by DaDarkWizard** [comment]
Outdated
